version: "3.8"

services:

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8081:8080"
    environment:
      STREAM_KEY: ${STREAM_KEY} 

  snapshot:
    image: jrottenberg/ffmpeg:4.4-ubuntu
    environment:
      STREAM_KEY: ${STREAM_KEY}
      SNAPSHOT_INTERVAL: ${SNAPSHOT_INTERVAL}
    volumes:
      - ./html:/data/html
      - ./snapshot.sh:/usr/local/bin/snapshot.sh:ro
    entrypoint: ["/usr/local/bin/snapshot.sh"]
    network_mode: "service:nginx"
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
    ports:
      - "1935:1935"
    volumes:
      - ./hls:/data/hls
      - ./html:/data/html:ro
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      STREAM_KEY: ${STREAM_KEY}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./hls:/data/hls:ro
      - ./html:/data/html:ro
    depends_on:
      - nginx

volumes:
  caddy_data:
  caddy_config:
